export { fetchStats, fetchRecentActivities } from './dashboard'
export type { RecentActivitiesResponse } from './dashboard'
export { register, login, fetchMe, updateMe, logout, fetchUsers } from './auth'
export type { RegisterPayload, LoginPayload, LoginResponse, UserResponse, UserRole, UpdateMePayload } from './auth'
export { fetchClients, createClient, updateClient, fetchRandomClientPayload, deleteClient } from './clients'
export type { ClientPayload, PaginationParams, PaginatedResult, ClientFilters } from './clients'
export { fetchTasks, createTask, updateTask, fetchRandomTaskPayload, deleteTask } from './tasks'
export type { TaskPayload, TaskFilters } from './tasks'
export type { StatsResponse, TaskStatusCount, Client, ClientStatus, Task, TaskStatus, TaskPriority } from './types'
